name = "tally-mcp-server"
main = "dist/worker.js"
compatibility_date = "2023-10-30"
node_compat = true

# Environment variables and secrets are configured via wrangler CLI:
# echo "YOUR_TALLY_API_KEY" | npx wrangler secret put TALLY_API_KEY
# echo "your_unique_auth_token" | npx wrangler secret put AUTH_TOKEN

# To customize the deployment subdomain, change the 'name' field above
# This will deploy to: https://tally-mcp-server.workers.dev/mcp

[build]
command = "npm run build:worker"

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"
TALLY_BASE_URL = "https://api.tally.so"
PORT = "8787"
HOST = "0.0.0.0"
DEBUG = "false"
REQUEST_TIMEOUT = "30000"
MAX_CONNECTIONS = "100"
CORS_ENABLED = "true"
ALLOWED_ORIGINS = "*"
LOG_LEVEL = "info"
LOG_COMPONENT = "MCPServer"
LOG_ENABLE_CONSOLE = "true"
LOG_ENABLE_STRUCTURED = "true"
LOG_REDACT_SENSITIVE = "true"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"
SECURITY_HELMET_ENABLED = "true" 